### PR TITLE
feat: migrate to vite-ts [Break-Changes]

### PR DESCRIPTION
**Pull request by kamikazebr**
- [x] Migrated from javascript to typescript
- [x] Migrated from react-app to vite-ts-app
- [x] Fixed subgraph and bumped graph-node
- [x] Another small fixes.

---
- [x] Fixed Git Actions, disabled nodev16
- [x] Published Contracts and Subgraph Rinkeby
- [x] Fixed Router
- [x] Fixed Subgraph UI
- [x] And alot others little things.

### CODE REVIEW

**Comment by reznord** [comment]
just nitpicking: we might not want to commit all the vscode related folders (`.vscode`, `vscode workspace files` etc). Will take a deep look into this one this weekend.

**Comment by kamikazebr** [comment]
> just nitpicking: we might not want to commit all the vscode related folders (`.vscode`, `vscode workspace files` etc). Will take a deep look into this one this weekend.

Do not worry (used wrong word before), that use templates from scaffold-eth and have some good patterns and that branch its not to do that kind changes for now. immo

**Comment by kamikazebr** [comment]
What will be awesome is understand why Vercel its not deploying it correctly @reznord 

image

---

```
<html>
<body>
<!--StartFragment-->

src/components/Modals/Add.tsx(53,30): error TS2339: Property 'createVestedERC20' does not exist on type 'BaseContract'.
--
01:21:56.995 | src/components/Modals/Wrap.tsx(24,32): error TS2339: Property 'approve' does not exist on type 'BaseContract'.
01:21:56.995 | src/components/main/MainPageFooter.tsx(50,13): error TS2322: Type 'TypeNetworkInfo \| undefined' is not assignable to type 'TNetworkInfo \| undefined'.
01:21:56.995 | Property 'url' is missing in type 'TypeNetworkInfo' but required in type 'TNetworkInfo'.
01:21:56.996 | src/config/contractConnectorConfig.ts(3,34): error TS2307: Cannot find module '../generated/hardhat_contracts.json' or its corresponding type declarations.
01:21:56.996 | src/config/contractConnectorConfig.ts(7,35): error TS2307: Cannot find module '~~/generated/contract-types' or its corresponding type declarations.
01:21:56.996 | src/config/contractContext.ts(28,3): error TS2344: Type '{ readonly VestedERC20Factory: Readonly<{ contractName: "VestedERC20Factory"; config: TBasicContractDataConfig; } & Readonly<{ connect: (address: string, signerOrProvider: Signer \| Provider) => BaseContract; abi: readonly Record<...>[]; }>>; readonly VestedERC20: Readonly<...>; readonly TestERC20: Readonly<...>; }' does not satisfy the constraint 'TConnectorList<"VestedERC20Factory" \| "VestedERC20" \| "TestERC20", TBaseContractExtended<"VestedERC20Factory" \| "VestedERC20" \| "TestERC20">>'.

<!--EndFragment-->
</body>
</html>
```

**Review by 0xGabi — APPROVED** [review]

**Comment by 0xGabi** [comment]
Let's merge this awesome PR and start doing some improvements on the UI 💪

**Pull request merged**
